function customizedFigureOpen
figure;
set (gcf, 'DefaultTextFontName', 'Verdana', ...
    'DefaultTextFontSize', 14, ...
    'DefaultAxesFontName', 'Verdana', ...
    'DefaultAxesFontSize', 14, ...
    'DefaultLineMarkerSize', 10);
end